{{- if not .Values.PubSub.RmqConnectionString}}
{{- if .Values.rabbitMQ.certificates.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "invictus.fullname" . }}-certs
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.rabbitMQ.certificates -}}
  {{- if .cacert }}
  cacert: |
    {{ .cacert | b64enc }}
  {{- end }}
  {{- if .cert }}
  cert: |
    {{ .cert | b64enc }}
  {{- end }}
  {{- if .key }}
  key: |
    {{ .key | b64enc }}
  {{- end }}
  {{- range $cert := .extraCerts }}
  {{ $cert.name }}: |
    {{ $cert.cert | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
