{{- if or (not .Values.existingSQLConnectionString) (not .Values.existingDurableSQLConnectionString)}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mssql"
  labels:
    app: {{ template "invictus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.SQL.deployment.labels }}
{{ toYaml .Values.SQL.deployment.labels | indent 4 }}
{{- end }}
{{- if .Values.SQL.deployment.annotations }}
  annotations:
{{ toYaml .Values.SQL.deployment.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.SQL.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "invictus.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "invictus.name" . }}
        release: {{ .Release.Name }}
{{- if .Values.SQL.pod.labels }}
{{ toYaml .Values.SQL.pod.labels | indent 8 }}
{{- end }}
{{- if .Values.SQL.pod.annotations }}
      annotations:
{{ toYaml .Values.SQL.pod.annotations | indent 8 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10001
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.SQL.image.repository }}:{{ .Values.SQL.image.tag }}"
          {{- if .Values.SQL.image.pullSecrets }}
          imagePullSecrets:
    {{ toYaml .Values.SQL.image.pullSecrets | indent 10 }}
          {{- end }}
          imagePullPolicy: {{ .Values.SQL.image.pullPolicy }}
          env:
            - name: ACCEPT_EULA
              value: "{{ .Values.SQL.acceptEula.value | upper }}"
            - name: MSSQL_PID
              value: "{{ .Values.SQL.edition.value }}"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: sapassword
            - name: MSSQL_DATA_DIR
              value: {{ .Values.SQL.dataDir }}
            - name: MSSQL_TCP_PORT
              value: "{{ .Values.SQL.service.port }}"
            - name: MSSQL_COLLATION
              value: "{{ .Values.SQL.collation }}"
            - name: MSSQL_LCID
              value: "{{ .Values.SQL.lcid }}"
            - name: MSSQL_ENABLE_HADR
              value: "{{ .Values.SQL.hadr }}"
            {{ if .Values.SQL.resources.limits.memory }}
            - name: MSSQL_MEMORY_LIMIT_MB
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Mi
            {{ end }}
          ports:
            - name: mssql
              containerPort: {{ .Values.SQL.service.port }}
          volumeMounts:
            - name: data
              mountPath: /var/opt/mssql
          livenessProbe:
            tcpSocket:
              port: mssql
            initialDelaySeconds: {{ .Values.SQL.livenessprobe.initialDelaySeconds }}
            periodSeconds: {{ .Values.SQL.livenessprobe.periodSeconds }}
          readinessProbe:
            tcpSocket:
              port: mssql
            initialDelaySeconds: {{ .Values.SQL.readinessprobe.initialDelaySeconds }}
            periodSeconds: {{ .Values.SQL.readinessprobe.periodSeconds }}
          resources:
{{ toYaml .Values.SQL.resources | indent 12 }}
    {{- if .Values.SQL.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.SQL.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: data
      {{- if .Values.SQL.persistence.enabled }}
        persistentVolumeClaim:
          {{- if .Values.SQL.persistence.existingDataClaim }}
          claimName: {{ .Values.SQL.persistence.existingDataClaim }}
          {{- else }}
          claimName: mssql-data
          {{- end -}}
      {{- else }}
        emptyDir: {}
      {{- end }}
{{- end }}