{{- if not .Values.PubSub.RmqConnectionString}}
{{ $plugins := compact (list "") }}
{{- if .Values.rabbitMQ.k8sPeerDiscoveryPlugin.enabled }}
{{ $plugins = append $plugins "rabbitmq_peer_discovery_k8s" }}
{{- end }}
{{- if .Values.rabbitMQ.managementPlugin.enabled }}
{{ $plugins = append $plugins "rabbitmq_management" }}
{{- end }}
{{- if .Values.rabbitMQ.prometheusPlugin.enabled }}
{{ $plugins = append $plugins "rabbitmq_prometheus"}}
{{- end }}
{{- if .Values.rabbitMQ.plugins }}
{{ $plugins = concat $plugins .Values.rabbitMQ.plugins }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-plugins
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
data:
  enabled_plugins: |
    [{{- join "," $plugins }}].
{{- end }}