{{- if or (not .Values.existingSQLConnectionString) (not .Values.existingDurableSQLConnectionString)}}
{{- if and .Values.SQL.persistence.enabled (not .Values.SQL.persistence.existingDataClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-data
  labels:
    app: {{ template "invictus.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.SQL.persistence.annotations -}}
    annotations:
    {{ toYaml .Values.SQL.persistence.annotations | indent 4 }}
    {{- end }}    
spec:
{{- if .Values.SQL.persistence.storageClass }}
{{- if (eq "-" .Values.SQL.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.SQL.persistence.storageClass }}"
{{- end }}
{{- end }}
  capacity:
    storage: {{ .Values.SQL.persistence.dataSize | quote }}
  accessModes:
    - {{ .Values.SQL.persistence.dataAccessMode | quote }}
  hostPath:
    path: "/mnt/data"
{{- end -}}
{{- end }}    