apiVersion: v1
kind: Secret
metadata:
  name: regextranslation-function-keys
type: Opaque
data:
  host.master: {{ include "RegexTranslation-hostmaster-function-key" .| b64enc | quote}}
  function.HttpTrigger.default: {{ include "RegexTranslation-HttpTrigger-function-key" .| b64enc | quote}}