{{- if not .Values.PubSub.RmqConnectionString}}
{{- if .Values.rabbitMQ.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rabbitmq-endpoint-reader
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
#  - apiGroups: [""]
#    resources: ["events"]
#    verbs: ["create"]
{{- end }}
{{- end }}