{{- if or (not .Values.existingSQLConnectionString) (not .Values.existingDurableSQLConnectionString)}}
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  labels:
    app: {{ template "invictus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  sapassword:  {{ .Values.SQL.sapassword | b64enc | quote }}
{{- end }}