apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
subjects:
- kind: ServiceAccount
  name: invictus-secret-reader
  apiGroup: ""
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io