apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.SequenceController.OpenApiInfoTitle |lower | nospace}}
  labels:
    app: {{ template "invictus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "invictus.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "invictus.name" . }}
        release: {{ .Release.Name }}
        function: {{ .Values.SequenceController.OpenApiInfoTitle |lower | nospace}}
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10005
      containers:
        - name: "sequencecontl"
          image: "{{ .Values.SequenceController.image.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          volumeMounts:
          - name: sequencecontroller-function-keys
            mountPath: "/azure-functions-host/Secrets"
            readOnly: true
          env:
            - name: "SQLDB_DurableState_Connection"
              valueFrom:
                secretKeyRef:
                  key : SqlFilesConnectionString
                  name: sequenceconfig
            - name: "FUNCTIONS_WORKER_RUNTIME"
              valueFrom:
               secretKeyRef:
                key : FUNCTIONS_WORKER_RUNTIME
                name: sequenceconfig
            - name: "WEBSITE_SLOT_NAME"
              valueFrom:
               secretKeyRef:
                key : WEBSITE_SLOT_NAME
                name: sequenceconfig                
            - name: "FUNCTIONS_EXTENSION_VERSION"
              valueFrom:
               secretKeyRef:
                key : FUNCTIONS_EXTENSION_VERSION
                name: sequenceconfig    
            - name: "ScmType"
              valueFrom:
               secretKeyRef:
                key : ScmType
                name: sequenceconfig    
            - name: "WEBSITE_AUTH_ENABLED"
              valueFrom:
               secretKeyRef:
                key : WEBSITE_AUTH_ENABLED
                name: sequenceconfig                                    
            - name: "REMOTEDEBUGGINGVERSION"
              valueFrom:
               secretKeyRef:
                key : REMOTEDEBUGGINGVERSION
                name: sequenceconfig  
            - name: "APPINSIGHTS_INSTRUMENTATIONKEY"
              valueFrom:
               secretKeyRef:
                key : APPINSIGHTS_INSTRUMENTATIONKEY
                name: sequenceconfig  
            - name: "InvictusDashboardConnectionString"
              valueFrom:
               secretKeyRef:
                key : InvictusDashboardConnectionString
                name: sequenceconfig  
            - name: "WEBSITE_SITE_NAME"
              valueFrom:
               secretKeyRef:
                key : WEBSITE_SITE_NAME
                name: sequenceconfig  
            - name: "WEBSITE_AUTH_LOGOUT_PATH"
              valueFrom:
               secretKeyRef:
                key : WEBSITE_AUTH_LOGOUT_PATH
                name: sequenceconfig  
            - name: "AzureWebJobsStorage" 
            - name: "OpenApi__Info__Version"
              valueFrom:
               secretKeyRef:
                key : OpenApi__Info__Version
                name: sequenceconfig  
            - name: "OpenApi__Info__Title"
              valueFrom:
               secretKeyRef:
                key : OpenApi__Info__Title
                name: sequenceconfig  
            - name: "RunningEnvironment"
              valueFrom:
               secretKeyRef:
                key : RunningEnvironment
                name: sequenceconfig  
            - name: "SqlFilesConnectionString"
              valueFrom:
               secretKeyRef:
                key : SqlFilesConnectionString
                name: sequenceconfig
            - name: "SQLDB_DurableState_Connection"
              valueFrom:
               secretKeyRef:
                key : SQLDB_DurableState_Connection
                name: sequenceconfig   
            - name: "AzureWebJobsSecretStorageType"
              valueFrom:
               secretKeyRef:
                key : AzureWebJobsSecretStorageType
                name: sequenceconfig    
            - name: "AzureWebJobsKubernetesSecretName"
              valueFrom:
               secretKeyRef:
                key : AzureWebJobsKubernetesSecretName
                name: sequenceconfig                    

          ports:
            - name: sequencecontrol
              containerPort: {{ .Values.port }}
            - name: http
              protocol: TCP
              containerPort: 80
      volumes:
      - name: sequencecontroller-function-keys
        secret:
          secretName: sequencecontroller-function-keys              
      imagePullSecrets:
       - name: myregistrykey              