{{- if not .Values.existingSQLConnectionString}}
apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: {{ template "invictus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.SQL.service.labels }}
{{ toYaml .Values.SQL.service.labels | indent 4 }}
{{- end }}
{{- if .Values.SQL.service.annotations }}
  annotations:
{{ toYaml .Values.SQL.service.annotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.SQL.service.headless }}
  type: ClusterIP
  clusterIP: None
  {{- else }}
  type: {{ .Values.SQL.service.type }}
  {{- end }}
  ports:
  - name: mssql
    port: {{ .Values.SQL.service.port }}
    targetPort: mssql
    protocol: TCP
  selector:
    app: {{ template "invictus.name" . }}
    release: {{ .Release.Name }}
{{- end }}