{{- if not .Values.PubSub.RmqConnectionString}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
  serviceName: rabbitmq-internal
  podManagementPolicy: {{ .Values.rabbitMQ.podManagementPolicy }}
  replicas: {{ .Values.rabbitMQ.replicaCount }}
{{- if .Values.rabbitMQ.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.rabbitMQ.revisionHistoryLimit }}
{{- end }}
  updateStrategy:
    type: {{ .Values.rabbitMQ.updateStrategyType }}
  template:
    metadata:
      annotations:
        checksum/rabbit-config: {{ include (print $.Template.BasePath "/rabbit-config.yaml") . | sha256sum }}
        checksum/plugins-config: {{ include (print $.Template.BasePath "/plugins-config.yaml") . | sha256sum }}
        checksum/scripts: {{ include (print $.Template.BasePath "/scripts.yaml") . | sha256sum }}
        checksum/certs: {{ include (print $.Template.BasePath "/certs.yaml") . | sha256sum }}
    {{- with .Values.rabbitMQ.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "rabbitmq.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "rabbitmq.serviceAccountName" . }}
      {{- with .Values.rabbitMQ.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rabbitMQ.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          {{- with .Values.rabbitMQ.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.rabbitMQ.initImage.registry }}/{{ .Values.rabbitMQ.initImage.repository }}:{{ .Values.rabbitMQ.initImage.tag }}"
          imagePullPolicy: {{ .Values.rabbitMQ.initImage.pullPolicy }}
          env:
            {{- if .Values.rabbitMQ.authentication.erlangCookie }}
            - name: ERLANG_COOKIE
              value: {{ .Values.rabbitMQ.authentication.erlangCookie }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/rabbitmq
            {{- if .Values.rabbitMQ.extraSecretConfigs }}
            - mountPath: /extraconfigs
              name: extraconfigs-volume
            {{- end }}
            {{- if .Values.rabbitMQ.extraSecretAdvancedConfigs }}
            - mountPath: /extraadvancedconfigs
              name: extraadvancedconfigs-volume
            {{- end }}
            - name: rabbitconfig
              mountPath: /temp/rabbitmq
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq
            - name: scripts
              mountPath: /scripts
            - name: plugins
              mountPath: /temp/plugins
          command: [ "/scripts/init.sh" ]
      {{- with .Values.rabbitMQ.extraInitContainers }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.rabbitMQ.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.rabbitMQ.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with  .Values.rabbitMQ.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.rabbitMQ.image.registry }}/{{ .Values.rabbitMQ.image.repository }}:{{ .Values.rabbitMQ.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rabbitMQ.image.pullPolicy }}
          ports:
            - name: amqp
              containerPort: {{ .Values.rabbitMQ.options.tcp.port }}
            {{- if .Values.rabbitMQ.options.ssl.enabled }}
            - name: amqps
              containerPort: {{ .Values.rabbitMQ.options.ssl.port }}
            {{- end }}
            {{- if .Values.rabbitMQ.managementPlugin.enabled }}
            - name: mgmt
              containerPort: {{ .Values.rabbitMQ.managementPlugin.tcp.port }}
            {{- end }}
            {{- if .Values.rabbitMQ.prometheusPlugin.enabled }}
            - name: prometheus
              containerPort: {{ .Values.rabbitMQ.prometheusPlugin.tcp.port }}
            {{- end }}
            - name: epmd
              containerPort: 4369
            - name: dist
              containerPort: 25672
            {{- range $service := .Values.rabbitMQ.extraServices }}
            - name: {{ $service.name }}
              containerPort: {{ $service.containerPort}}
              protocol: {{ $service.protocol }}
            {{- end }}
          {{- if .Values.rabbitMQ.customStartupProbe }}
          startupProbe:
            {{- toYaml .Values.rabbitMQ.customStartupProbe | nindent 12 }}
          {{- else }}
          {{- if .Values.rabbitMQ.startupProbe.enabled }}
          startupProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - rabbitmq-diagnostics -q check_running
          {{- with .Values.rabbitMQ.startupProbe }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            successThreshold: {{ .successThreshold }}
            periodSeconds: {{ .periodSeconds }}                
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.rabbitMQ.customLivenessProbe }}
          livenessProbe:
            {{- toYaml .Values.rabbitMQ.customLivenessProbe | nindent 12 }}
          {{- else }}
          {{- if .Values.rabbitMQ.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - rabbitmq-diagnostics -q check_running
          {{- with .Values.rabbitMQ.livenessProbe }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
            successThreshold: {{ .successThreshold }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.rabbitMQ.customReadinessProbe }}
          readinessProbe:
            {{- toYaml .Values.rabbitMQ.customReadinessProbe | nindent 12 }}
          {{- else }}
          {{- if .Values.rabbitMQ.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - rabbitmq-diagnostics -q check_running
          {{- with .Values.rabbitMQ.readinessProbe }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
            successThreshold: {{ .successThreshold }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.rabbitMQ.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          lifecycle:
          {{- if gt (.Values.rabbitMQ.replicaCount | int) 1 }}
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -ec
                  - /scripts/startup.sh
          {{- end }}
            preStop:
              exec:
                command:
                  - bash
                  - -ec
                  - /scripts/shutdown.sh
          env:
            - name: RABBITMQ_USE_LONGNAME
              value: {{ .Values.rabbitMQ.clustering.useLongName | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if .Values.rabbitMQ.clustering.useLongName }}
            - name: RABBITMQ_NODENAME
              value: rabbit@$(NODE_NAME).rabbitmq-internal.{{ .Release.Namespace }}.svc.{{ .Values.rabbitMQ.clusterDomain }}
            {{- else }}
            - name: RABBITMQ_NODENAME
              value: rabbit@$(NODE_NAME)
            {{- end }}
          {{- with .Values.rabbitMQ.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
          {{- range .Values.rabbitMQ.extraEnvSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}          
          {{- if .Values.rabbitMQ.args }}
          args:
            {{- range .Values.rabbitMQ.args }}
            - {{ . }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: logs
              mountPath: /var/log/rabbitmq
            - name: tmp
              mountPath: /tmp
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq
            - name: config
              mountPath: /etc/rabbitmq
            - name: scripts
              mountPath: /scripts
            {{- if .Values.rabbitMQ.certificates.enabled }}
            - name: certs
              mountPath: /ssl
            {{- end }}
            {{- range $secret := .Values.rabbitMQ.extraSecrets }}
            - name: {{ $secret.name }}
              mountPath: {{ $secret.mountPath }}
            {{- end }}
      {{- with .Values.rabbitMQ.extraContainers }}
      {{- toYaml . | nindent 8 }}
      {{- end }} 
      {{- with .Values.rabbitMQ.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rabbitMQ.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rabbitMQ.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: config
          emptyDir: {}
        - name: rabbitconfig
          configMap:
            name: rabbitmq-config
        {{- if .Values.rabbitMQ.extraSecretConfigs }}
        - name: extraconfigs-volume
          secret:
            secretName: {{ .Values.rabbitMQ.extraSecretConfigs }}
        {{- end }}
        {{- if .Values.rabbitMQ.extraSecretAdvancedConfigs }}
        - name: extraadvancedconfigs-volume
          secret:
            secretName: {{ .Values.rabbitMQ.extraSecretAdvancedConfigs }}
        {{- end }}
        - name: scripts
          configMap:
            name: rabbitmq-scripts
            defaultMode: 0555
        - name: plugins
          configMap:
            name: rabbitmq-plugins
        {{- if .Values.rabbitMQ.certificates.enabled }}
        - name: certs
          secret:
            secretName: rabbitmq-certs
            defaultMode: 0440
        {{- end }}
        {{- range $secret := .Values.rabbitMQ.extraSecrets }}
        - name: {{ $secret.name }}
          secret:
            secretName: {{ $secret.name }}
            defaultMode: 0440
        {{- end }}
  {{- if .Values.rabbitMQ.storage.persistentVolumeClaimName }}
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: {{ .Values.rabbitMQ.storage.persistentVolumeClaimName }}
  {{- else }}
  {{- if not .Values.rabbitMQ.storage.requestedSize }}
        - name: rabbitmq-volume
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-volume
      spec:
        {{- with .Values.rabbitMQ.storage.accessModes }}
        accessModes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.rabbitMQ.storage.className }}
        storageClassName: {{ .Values.rabbitMQ.storage.className }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.rabbitMQ.storage.requestedSize }}
  {{- end }}
  {{- end }}
{{- end }}